[#feat] Add example to describe Airflow DAG using yaml odahu resource…
odahu/odahu-examples pull request #2
Opened 2019-11-27 12:49 UTC by vlad-tokarev

… definition files

2019-11-27 13:28 UTC, maxkochubey approved these changes

2019-11-27 13:28 UTC, maxkochubey commented on mlflow/sklearn/wine/airflow/dag_from_yamls/training.odahuflow.yaml
> +      memory: 2024Mi
Please consider values in a more familiar form :)
```
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 2
      memory: 2Gi
```

2019-11-27 22:59 UTC, mcdoker18 requested changes

2019-11-27 22:59 UTC, mcdoker18 commented on mlflow/sklearn/wine/airflow/dag_from_yamls/dag_from_yamls.py
> +
We need a little documentation or link to the documentation here. This doc should explain how to package the dag and yamls file and to deploy it to a composer.

2019-11-27 22:59 UTC, mcdoker18 commented on mlflow/sklearn/wine/airflow/dag_from_yamls/dag_from_yamls.py
> +edi_connection_id = "odahuflow_edi"
`edi` -> `api`

2019-12-03 21:13 UTC, mcdoker18 requested changes

2019-12-03 21:13 UTC, mcdoker18 commented on mlflow/sklearn/wine/airflow/dag_from_yamls/dag_from_yamls.py
> +    odahuflow_conn = GcpConnectionToLegionConnectionOperator(
Odahu

2019-12-08 14:38 UTC, mcdoker18 requested changes

2019-12-08 14:38 UTC, mcdoker18 commented on mlflow/tensorflow/example/airflow/dag.py
> +        edi_connection_id=api_connection_id,
Rename the `edi_connection_id` in all files as well.

2019-12-09 09:10 UTC, mcdoker18 approved these changes

2019-12-10 07:12 UTC, merged