[fix] Updated path to manifest from wine DAG
odahu/odahu-examples pull request #24
Opened 2020-03-27 17:27 UTC by mcdoker18

2020-03-27 17:28 UTC, karbyshevds approved these changes

2020-03-30 13:44 UTC, vlad-tokarev approved these changes

2020-04-01 11:28 UTC, maxkochubey approved these changes

2020-04-01 15:57 UTC, karbyshevds requested changes
I've found an issue, when using git-sync, DAGs syncing to separate directory /usr/local/airflow/dags/, so Airflow worker invokes it with path like `/usr/local/airflow/dags/mlflow/sklearn/wine/airflow/dag_from_yamls/dag_from_yamls.py` which is trying to open access yaml file via wrong path (mlflow/sklearn/wine/airflow/dag_from_yamls/wine_training.odahuflow.yaml)

full log:
```
[2020-04-01 15:53:44,526] {{dagbag.py:232}} DEBUG - Importing /usr/local/airflow/dags/mlflow/sklearn/wine/airflow/dag_from_yamls/dag_from_yamls.py
[2020-04-01 15:53:44,530] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/mlflow/sklearn/wine/airflow/dag_from_yamls/dag_from_yamls.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/mlflow/sklearn/wine/airflow/dag_from_yamls/dag_from_yamls.py", line 22, in <module>
    training_id, training = resource('mlflow/sklearn/wine/airflow/dag_from_yamls/wine_training.odahuflow.yaml')
  File "/usr/local/lib/python3.7/site-packages/odahuflow/airflow_plugin/resources.py", line 94, in resource
    pair = _parse_resource_body(resource_body)
  File "/usr/local/lib/python3.7/site-packages/odahuflow/airflow_plugin/resources.py", line 70, in _parse_resource_body
    resources = parse_stream(StringIO(resource_body))
  File "/usr/local/lib/python3.7/site-packages/odahuflow/sdk/clients/api_aggregated.py", line 199, in parse_stream
    raise ValueError('Invalid Odahuflow resource in file: {!r}'.format(item))
ValueError: Invalid Odahuflow resource in file: 'mlflow/sklearn/wine/airflow/dag_from_yamls/wine_training.odahuflow.yaml'
[2020-04-01 15:53:44,531] {{cli_action_loggers.py:86}} DEBUG - Calling callbacks: []
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 37, in <module>
    args.func(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 523, in run
    dag = get_dag(args)
  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 149, in get_dag
    'parse.'.format(args.dag_id))
airflow.exceptions.AirflowException: dag_id could not be found: airflow-wine-from-yamls. Either the dag did not exist or it failed to parse.
[2020-04-01 15:53:44,563] {{settings.py:278}} DEBUG - Disposing DB connection pool (PID 1)
```

2020-04-02 00:55 UTC, karbyshevds approved these changes

2020-04-06 15:53 UTC, xasm83 approved these changes

2020-04-07 15:16 UTC, merged